### ISSUE TITLE
Rename the package to pygpu?

### ISSUE THREAD

**Issue by abergeron** [conda-forge/libgpuarray-feedstock#2]
The name difference with the official conda package is causing some confusion amongst our users.

The problem is that many are doing `conda install Theano pygpu` and get Theano/python from conda-forge and pygpu/libgpuarray from official conda this way.  This often results in a non-functional install, especially on windows.

Maybe we could rename this package to pygpu to avoid the confusion issues.

I'm not sure how such things are handled in conda-forge which is why I made an issue to see if that was possible.

**Comment by jakirkham** [comment]
So IIUC in `defaults` there is a `libgpuarray` part that is just C and a `pygpu` part, which is a Python library that binds to `libgpuarray`, correct? Any thoughts on doing the same thing here?

**Comment by jakirkham** [comment]
Started the work in this direction with PR ( https://github.com/conda-forge/staged-recipes/pull/3142 ).

**Comment by jakirkham** [comment]
Once the next `libgpuarray` release is out, we will need to make some tweaks to this feedstock and the `pygpu` one. We can discuss more then when it happens.

In the interim, once `pygpu` is on `conda-forge`, we can add it as a dependency of `theano`. No further tweaks will be needed for `theano` (pertaining to this) after that switch is done.

**Comment by abergeron** [comment]
I agree with splitting the package, so this looks like it's going to be fixed soon.

**Comment by jakirkham** [comment]
Yeah, this should help set things up for splitting this package.

**Comment by jakirkham** [comment]
With `pygpu` now in, am switching `theano` to require `pygpu` in PR ( https://github.com/conda-forge/theano-feedstock/pull/12 ). Please take a look.

**Comment by jakirkham** [comment]
Have added PR ~~( https://github.com/conda-forge/libgpuarray-feedstock/pull/5 )~~ ( https://github.com/conda-forge/libgpuarray-feedstock/pull/7 ), which changes the `libgpuarray` recipe to a simple C library (dropping all Python portions). Also releases `libgpuarray` ~~0.6.7~~ 0.6.8.

**Comment by jakirkham** [comment]
Also have PR ~~( https://github.com/conda-forge/pygpu-feedstock/pull/1 )~~ ( https://github.com/conda-forge/pygpu-feedstock/pull/2 ) ready, which changes `pygpu` into a Python/NumPy package (instead of a metapackage). Also releases `pygpu` ~~0.6.7~~ 0.6.8. This will only work after `libgpuarray` ~~0.6.7~~ 0.6.8 is released.

**Comment by jakirkham** [comment]
Have merged the `pygpu` change. Should have binaries rebuilt with correct splitting of C and Python components shortly.
